services:
  - type: web
    name: pu-chatbot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python rag_pipeline.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: ENV
        value: production
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**/*
